"""
Persistence for the editor workspace. Every API call runs in a fresh Python process, so the
active artifact, its version pointer and the chat live in output/workspace/state.json.

The workspace never edits a user's original file: opening copies it into
output/workspace/<artifact id>/, and every edit is saved there plus as a version snapshot.
"""
import json
import os
import re
import time
import uuid
from pathlib import Path
from typing import Any, Dict, List, Optional

from core.edit_schema import EditError

# Relative to the working directory, like the rest of the pipeline (the server runs Python from the repo root)
ROOT = Path(".")
WORKSPACE_DIR = ROOT / "output" / "workspace"
STATE_FILE = WORKSPACE_DIR / "state.json"
UPLOAD_DIR = ROOT / "templates_and_samples" / "uploads"
DEMO_DIR = ROOT / "templates_and_samples" / "demo"
TEMPLATE_DIR = ROOT / "templates_and_samples"
OUTPUT_DIR = ROOT / "output"
DOC_EXTENSIONS = {".docx": "docx", ".pptx": "pptx"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".gif"}
MAX_MESSAGES = 200
MAX_IMAGE_BYTES = 5 * 1024 * 1024

# (folder, group label, recursive?) — the only places a document may be opened from
OPEN_SOURCES = [(DEMO_DIR, "Demo files"), (UPLOAD_DIR, "Your uploads"), (OUTPUT_DIR, "Generated by the agents"),
                (TEMPLATE_DIR, "Templates")]


def empty_state() -> Dict[str, Any]:
    return {"active": None, "messages": [], "pending_image": None, "pending_choices": None, "last_target": None}


def load_state() -> Dict[str, Any]:
    try:
        with open(STATE_FILE, encoding="utf-8") as f:
            state = json.load(f)
        return {**empty_state(), **state} if isinstance(state, dict) else empty_state()
    except (OSError, json.JSONDecodeError):
        return empty_state()


def save_state(state: Dict[str, Any]) -> None:
    WORKSPACE_DIR.mkdir(parents=True, exist_ok=True)
    state["messages"] = state["messages"][-MAX_MESSAGES:]
    tmp = STATE_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(state, indent=1), encoding="utf-8")
    os.replace(tmp, STATE_FILE)


def add_message(state: Dict[str, Any], role: str, text: str, **extra: Any) -> Dict[str, Any]:
    message = {"id": uuid.uuid4().hex[:12], "role": role, "text": text, "ts": time.time(), **extra}
    state["messages"].append(message)
    return message


def _inside(path: Path, folder: Path) -> bool:
    try:
        path.relative_to(folder.resolve())
        return True
    except ValueError:
        return False


def safe_document_path(user_path: str) -> Path:
    """Resolves a user-supplied path and only allows .docx/.pptx files directly in the known folders."""
    path = (Path.cwd() / str(user_path)).resolve()
    if path.suffix.lower() not in DOC_EXTENSIONS:
        raise EditError("Only .docx and .pptx files can be opened in the editor.")
    if not any(path.parent == folder.resolve() for folder, _ in OPEN_SOURCES) or not path.is_file():
        raise EditError("That file is not available. Pick a document from the list or upload one.")
    return path


def safe_upload_path(user_path: str) -> Path:
    path = (Path.cwd() / str(user_path)).resolve()
    if not _inside(path, UPLOAD_DIR) or not path.is_file():
        raise EditError("The uploaded file could not be found.")
    return path


def list_artifacts() -> List[Dict[str, str]]:
    items: List[Dict[str, str]] = []
    for folder, group in OPEN_SOURCES:
        if not folder.is_dir():
            continue
        for path in sorted(folder.iterdir(), key=lambda p: p.name.lower()):
            if path.is_file() and path.suffix.lower() in DOC_EXTENSIONS:
                items.append({"path": relative(path), "name": path.name, "group": group,
                              "type": DOC_EXTENSIONS[path.suffix.lower()]})
    return items


def new_artifact_dir(name: str) -> Path:
    stem = re.sub(r"[^A-Za-z0-9_-]+", "_", Path(name).stem)[:40] or "document"
    folder = WORKSPACE_DIR / f"{stem}-{uuid.uuid4().hex[:8]}"
    folder.mkdir(parents=True, exist_ok=False)
    return folder


def working_path(active: Dict[str, Any]) -> Path:
    path = (Path.cwd() / active["working_path"]).resolve()
    if not _inside(path, WORKSPACE_DIR) or not path.is_file():
        raise EditError("The open document is missing. Please open it again.")
    return path


def relative(path: Path) -> str:
    return path.resolve().relative_to(Path.cwd()).as_posix()


def pending_image_bytes(state: Dict[str, Any]) -> Optional[bytes]:
    pending = state.get("pending_image")
    if not pending:
        return None
    try:
        return safe_upload_path(pending["path"]).read_bytes()
    except (EditError, OSError):
        return None
